---
- name: Enable EPEL Repository on CentOS 8
  ansible.builtin.dnf:
    name: epel-release
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and (ansible_facts['distribution_major_version'] == '8' or ansible_facts['distribution_major_version'] == '8')

- name: Enable EPEL Repository on CentOS 7
  ansible.builtin.yum:
    name: epel-release
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

- name: Add apptainer ppa (Ubuntu)
  ansible.builtin.apt_repository:
    repo: ppa:apptainer/ppa
  when: ansible_distribution == "Ubuntu"

- name: Install apptainer
  ansible.builtin.package:
    name: apptainer
  when: ansible_distribution == "Ubuntu" or ansible_os_family == "RedHat"

# Required for Ubuntu 23.10+ when apptainer is installed from Ubuntu PPA
# Ref: https://github.com/apptainer/apptainer/issues/2691#issuecomment-2610689935
# Ref: https://github.com/apptainer/apptainer/blob/main/INSTALL.md#apparmor-profile-ubuntu-2310
- name: Create apparmor profile if one doesn't exist
  copy:
    src: apptainer
    dest: /etc/apparmor.d/apptainer
    force: false
  notify: 'Reload apparmor'
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'noble'
